### ISSUE TITLE
What's environment.oktaPassword?

### ISSUE THREAD

**Issue by fardin01** [oktadev/okta-aws-cli-assume-role#330]
When I execute any `okta` command (e.g. `okta-aws`) The following exception is thrown:

`Exception in thread "main" java.lang.IllegalStateException: Stored username or password is invalid. at com.okta.tools.authentication.OktaAuthentication.getPrimaryAuthResponse(OktaAuthentication.java:134)`

Where is `environment.oktaPassword` coming from? Clearly the value has to be `null` but it isn't so the exception is thrown.

https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/21e55af63e31a820eb216aac58bdcb146f0e1296/src/main/java/com/okta/tools/authentication/OktaAuthentication.java#L133

**Comment by bogeylnj** [comment]
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/21e55af63e31a820eb216aac58bdcb146f0e1296/src/main/java/com/okta/tools/OktaAwsConfig.java#L66
